### ISSUE TITLE
DevTools doesn't detect .phalcon folder.

### ISSUE THREAD

**Issue by Niko9911** [phalcon/phalcon-devtools#1148]
### Expected and Actual Behavior

> Trying to create new model via devtools CLI. Using command `phalcon model`
> Phalcon says there is no .phalcon folder and asks if it can be created.
> I'll answer `y` for that and after that it will check if directory was created, but fails.
> So, it does create empty directory.
> When running again that script, it will ask if it can create .phalcon directory, 
> but fails, because directory is already made.

> Provide output if related

```php
xxxx@xxxx-126 /www $ phalcon model

Phalcon DevTools (3.2.11)

                                                                                                                
  Info: This command must be run inside a Phalcon project with a .phalcon directory. One was not found at /www  
                                                                                                                
                                                          
  Info: Shall I create the .phalcon directory now? (y/n)  
                                                          
y

Retrying command...
PHP Fatal error:  Uncaught Phalcon\Commands\DotPhalconMissingException: This command must be run inside a Phalcon project with a .phalcon directory. in /home/xxx/phalcon-devtools/scripts/Phalcon/Commands/CommandsListener.php:59
Stack trace:
#0 [internal function]: Phalcon\Commands\CommandsListener->beforeCommand(Object(Phalcon\Events\Event), Object(Phalcon\Commands\Builtin\Model), NULL)
#1 [internal function]: Phalcon\Events\Manager->fireQueue(Array, Object(Phalcon\Events\Event))
#2 /home/xxxx/phalcon-devtools/scripts/Phalcon/Script.php(112): Phalcon\Events\Manager->fire('command:beforeC...', Object(Phalcon\Commands\Builtin\Model))
#3 /home/xxx/phalcon-devtools/scripts/Phalcon/Script.php(151): Phalcon\Script->dispatch(Object(Phalcon\Commands\Builtin\Model))
#4 /home/xxx/phalcon-devtools/phalcon.php(80): Phalcon\Script->run()
#5 {main}
  thrown in /home/xxxx/phalcon-devtools/scripts/Phalcon/Commands/CommandsListener.php on line 59
```

> Provide minimal script to reproduce the issue
```shell
$ phalcon model
```

### Details

* System info and versions (if possible): (`phalcon info`)
```shell
Phalcon DevTools (3.2.11)

Environment:
  OS: Linux SERVER-126 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64
  PHP Version: 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.1
  PHP Extension Dir: /usr/lib/php/20160303
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.1/cli/php.ini
Versions:
  Phalcon DevTools Version: 3.2.11
  Phalcon Version: 3.2.2
  AdminLTE Version: 2.3.6
```

* Phalcon Framework version: (`php --ri phalcon`)
```shell
phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.2
Build Date => Sep  8 2017 05:04:34
Powered by Zephir => Version 0.9.9-868cb1f92b

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```
* Operating System:
```shell
$ uname -a
Linux xxxx-126 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ uname -r
4.8.0-53-generic

$ cat /proc/version
Linux version 4.8.0-53-generic (buildd@lgw01-56) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017

$ cat /etc/issue
Linux Mint 18.2 Sonya \n \l
```

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue. It works fine for me. `.phalcon` and model create very well. 
  Phalcon DevTools Version: 3.2.11
  Phalcon Version: 3.3.0
  AdminLTE Version: 2.3.6

If I could right understand - `.phalcon` was created but model didn't create. Could you take a look `.log` file?

**Comment by Niko9911** [comment]
Will check this issue ASAP. I'm just today and maybe tomorrow little too busy.

**Comment by Niko9911** [comment]
@sergeysviridenko 

Well, console gives this output:

```php
# phalcon model

Phalcon DevTools (3.2.11)

                                                                                                                                      
  Info: This command must be run inside a Phalcon project with a .phalcon directory. One was not found at /home/niko/Työpöytä/www  
                                                                                                                                      
                                                          
  Info: Shall I create the .phalcon directory now? (y/n)  
                                                          
y

Retrying command...
PHP Warning:  mkdir(): File exists in /home/niko/phalcon-devtools/scripts/Phalcon/Commands/DotPhalconMissingException.php on line 66
PHP Stack trace:
PHP   1. {main}() /home/niko/phalcon-devtools/phalcon.php:0
PHP   2. Phalcon\Commands\DotPhalconMissingException->promptResolution() /home/niko/phalcon-devtools/phalcon.php:79
PHP   3. Phalcon\Commands\DotPhalconMissingException->resolve() /home/niko/phalcon-devtools/scripts/Phalcon/Commands/DotPhalconMissingException.php:61
PHP   4. mkdir() /home/niko/phalcon-devtools/scripts/Phalcon/Commands/DotPhalconMissingException.php:66
PHP Fatal error:  Uncaught Phalcon\Commands\DotPhalconMissingException: This command must be run inside a Phalcon project with a .phalcon directory. in /home/niko/phalcon-devtools/scripts/Phalcon/Commands/CommandsListener.php:59
Stack trace:
#0 [internal function]: Phalcon\Commands\CommandsListener->beforeCommand(Object(Phalcon\Events\Event), Object(Phalcon\Commands\Builtin\Model), NULL)
#1 [internal function]: Phalcon\Events\Manager->fireQueue(Array, Object(Phalcon\Events\Event))
#2 /home/niko/phalcon-devtools/scripts/Phalcon/Script.php(112): Phalcon\Events\Manager->fire('command:beforeC...', Object(Phalcon\Commands\Builtin\Model))
#3 /home/niko/phalcon-devtools/scripts/Phalcon/Script.php(151): Phalcon\Script->dispatch(Object(Phalcon\Commands\Builtin\Model))
#4 /home/niko/phalcon-devtools/phalcon.php(80): Phalcon\Script->run()
#5 {main}
  thrown in /home/niko/phalcon-devtools/scripts/Phalcon/Commands/CommandsListener.php on line 59
```


Any ideas where I can find more info?

**Comment by Niko9911** [comment]
I can create .phalcon using webtools command.

**Comment by Niko9911** [comment]
`drwxrwxrwx  2 niko niko  4096 marra 17 09:45 .phalcon`

=> 

```
halcon DevTools (3.2.11)

                                                                                                                                      
  Info: This command must be run inside a Phalcon project with a .phalcon directory. One was not found at /home/niko/Työpöytä/www  
                                                                                                                                      
                                                          
  Info: Shall I create the .phalcon directory now? (y/n)  
```

**Comment by Niko9911** [comment]
@sergeysviridenko

Can you tell me where I can disable .phalcon check. If I could bypass that check it might help me find the real problem...

**Comment by oscarmolinadev** [comment]
@Niko9911 https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Commands/CommandsListener.php#L55

**Comment by Niko9911** [comment]
@oscarmolinadev Thanks!

Now I have this error: `Error: Builder doesn't know where is the models directory.` How I can set models location into config.json?

**Comment by oscarmolinadev** [comment]
Mmm.. you can put var_dump to see if direcotry exists?

https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Commands/Builtin/Model.php#L111

**Comment by Niko9911** [comment]
@oscarmolinadev 

```
/home/niko/phalcon-devtools/scripts/Phalcon/Commands/Builtin/Model.php:100:
string(14) "app/api/models"
```

**Comment by oscarmolinadev** [comment]
@Niko9911  You need modelsDir too.

https://github.com/phalcon/phalcon-devtools/blob/18e352c1db6d6875bdcbfede934266deaaa38013/scripts/Phalcon/Builder/Model.php#L156

**Comment by Niko9911** [comment]
@oscarmolinadev Can I set models fir into config.json? Is it possible?

**Comment by Niko9911** [comment]
I had to put full path to the models directory... 

```ini
[application]
modelsDir       = /home/niko/Työpöytä/www/app/api/models
```

**Comment by ninjapanzer** [comment]
@Niko9911 is this issue what spawned `https://github.com/phalcon/docs/issues/1417`

**Comment by sergeysviridenko** [comment]
@Niko9911 was your problem solved or still appear?

**Comment by Niko9911** [comment]
@sergeysviridenko This can be close. Tough phalcon/docs#1417 will continue.

**Comment by sergeysviridenko** [comment]
@Niko9911 Thank you.
