### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function tests_path()

### ISSUE THREAD

**Issue by andygithubchen** [phalcon/phalcon-devtools#1207]
I do "phalcon model products", show:

```
PHP Fatal error:  Uncaught Error: Call to undefined function tests_path() in /andydata/wwwroot/video/phalcon-devtools/tests/_data/console/app/mysql/config.php:15
Stack trace:
#0 /andydata/wwwroot/video/phalcon-devtools/scripts/Phalcon/Builder/Path.php(74): include()
#1 /andydata/wwwroot/video/phalcon-devtools/scripts/Phalcon/Commands/Builtin/Model.php(98): Phalcon\Builder\Path->getConfig()
#2 /andydata/wwwroot/video/phalcon-devtools/scripts/Phalcon/Script.php(117): Phalcon\Commands\Builtin\Model->run(Array)
#3 /andydata/wwwroot/video/phalcon-devtools/scripts/Phalcon/Script.php(151): Phalcon\Script->dispatch(Object(Phalcon\Commands\Builtin\Model))
#4 /andydata/wwwroot/video/phalcon-devtools/phalcon.php(76): Phalcon\Script->run()
#5 {main}
  thrown in /andydata/wwwroot/video/phalcon-devtools/tests/_data/console/app/mysql/config.php on line 15
```

**Comment by ariborneo** [comment]
how you do that?
