### ISSUE TITLE
Call to undefined method Phalcon\Config::has() in .../phalcon-devtools/src/Builder/Component/Project.php:60

### ISSUE THREAD

**Issue by izapantis22** [phalcon/phalcon-devtools#1424]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior
Success!

> **Describe what you are trying to achieve and what goes wrong.**
Trying to create my first project (phalcon project test) with phalcon and I'm getting an error for undefined method

> Provide output if related

```php
Phalcon DevTools (4.0.1)

PHP Fatal error:  Uncaught Error: Call to undefined method Phalcon\Config::has() in /home/ioannis/Documents/phalcon-devtools/src/Builder/Component/Project.php:60
Stack trace:
#0 /home/ioannis/Documents/phalcon-devtools/src/Commands/Builtin/Project.php(74): Phalcon\DevTools\Builder\Component\Project->build()
#1 /home/ioannis/Documents/phalcon-devtools/src/Script.php(109): Phalcon\DevTools\Commands\Builtin\Project->run(Array)
#2 /home/ioannis/Documents/phalcon-devtools/src/Script.php(148): Phalcon\DevTools\Script->dispatch(Object(Phalcon\DevTools\Commands\Builtin\Project))
#3 /home/ioannis/Documents/phalcon-devtools/phalcon(64): Phalcon\DevTools\Script->run()
#4 {main}
  thrown in /home/ioannis/Documents/phalcon-devtools/src/Builder/Component/Project.php on line 60
```

### Details

* System info and versions (if possible): 
```
Phalcon DevTools (4.0.1)

Environment:
  OS: Linux ioannis 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64
  PHP Version: 7.3.14-1+ubuntu19.10.1+deb.sury.org+1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.3
  PHP Extension Dir: /usr/lib/php/20180731
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.3/cli/php.ini
Versions:
  Phalcon DevTools Version: 4.0.1
  Phalcon Version: 3.4.5
  AdminLTE Version: 2.3.6
```

* Phalcon Framework version: (`php --ri phalcon`)
```
phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.5
Build Date => Jan 19 2020 13:22:06
Powered by Zephir => Version 0.10.16-6826149172

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```
* PHP Version: (`php -v`)
```
PHP 7.3.14-1+ubuntu19.10.1+deb.sury.org+1 (cli) (built: Jan 23 2020 13:59:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1+ubuntu19.10.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
* Operating System: Ubuntu 19.10
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by Jeckerson** [comment]
You phalcon version if not the same as devtools.

```
Phalcon DevTools Version: 4.0.1
Phalcon Version: 3.4.5
```

Use Phalcon `4.0.x` instead of `3.4.5`
