### ISSUE TITLE
 Error when working DevTools

### ISSUE THREAD

**Issue by Sa1ch** [phalcon/phalcon-devtools#1517]
I have installed:

PHP Version: 7.3.22
Phalcon DevTools Version: 4.0.6
Phalcon Version: 4.0.6

After I installed swiftmailer via Composer I can't create a model and controller.

If you execute the command: phalcon controller testName

I see a mistake

PHP Warning:  Invalid argument supplied for foreach() in /home/public_html/vendor/swiftmailer/swiftmailer/lib/swiftmailer_generate_mimes_config.php on line 133
PHP Fatal error:  Uncaught TypeError: Return value of Phalcon\DevTools\Builder\Path::getConfig() must be an instance of Phalcon\Config, int returned in /root/vendor/phalcon/devtools/src/Builder/Path.php:68
Stack trace:
#0 /root/vendor/phalcon/devtools/src/Builder/Component/AbstractComponent.php(86): Phalcon\DevTools\Builder\Path->getConfig('ini')
#1 /root/vendor/phalcon/devtools/src/Builder/Component/Controller.php(57): Phalcon\DevTools\Builder\Component\AbstractComponent->getConfig()
#2 /root/vendor/phalcon/devtools/src/Commands/Builtin/Controller.php(63): Phalcon\DevTools\Builder\Component\Controller->build()
#3 /root/vendor/phalcon/devtools/src/Script.php(109): Phalcon\DevTools\Commands\Builtin\Controller->run(Array)
#4 /root/vendor/phalcon/devtools/src/Script.php(148): Phalcon\DevTools\Script->dispatch(Object(Phalcon\DevTools\Commands\Builtin\Controller))
#5 /root/vendor/phalcon/devtools/phalcon(65): Phalcon\DevTools\Script->run()
#6 {main}
  thrown in /root/vendor/phalcon/devtools/src/Builder/Path.php on line 68

what could be the problem?

**Comment by Sa1ch** [comment]
Thanks to all! I figured out ☺
I used the command: phalcon controller test --output =app/controllers/
