### ISSUE TITLE
Phalcon 5 support on PHP 8.1

### ISSUE THREAD

**Issue by furopi** [phalcon/phalcon-devtools#1531]
Dear Sir,

could you please give an update of when the P5 support is estimated to arrive?

Thank you and kind regards,
Florian

**Comment by sollosollo4** [comment]
And i also have issue on php 8.0.5 when try to exec command `phalcon project test`

PHP Fatal error:  Uncaught Error: Class "Phalcon\Config" not found in D:\domains\phalcon-project\vendor\phalcon\devtools\src\Builder\Component\AbstractComponent.php:48
Stack trace:
#0 D:\domains\phalcon-project\vendor\phalcon\devtools\src\Commands\Builtin\Project.php(74): Phalcon\DevTools\Builder\Component\AbstractComponent->__construct()
#1 D:\domains\phalcon-project\vendor\phalcon\devtools\src\Script.php(109): Phalcon\DevTools\Commands\Builtin\Project->run()
#2 D:\domains\phalcon-project\vendor\phalcon\devtools\src\Script.php(148): Phalcon\DevTools\Script->dispatch()
#3 D:\domains\phalcon-project\vendor\phalcon\devtools\phalcon(65): Phalcon\DevTools\Script->run()
#4 {main}
  thrown in D:\domains\phalcon-project\vendor\phalcon\devtools\src\Builder\Component\AbstractComponent.php on line 48
Script phalcon handling the __exec_command event returned with error code 255



Environment:
  OS: Windows NT DESKTOP-6O57L8K 10.0 build 19044 (Windows 10) AMD64
  PHP Version: 8.0.5
  PHP SAPI: cli
  PHP Bin: C:\Program Files (x86)\php8\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: C:\Program Files (x86)\php8\php.ini
Versions:
  Phalcon DevTools Version: 4.2.0
  Phalcon Version: 5.1.4
  AdminLTE Version: 3.0.1

**Comment by sollosollo4** [comment]
ok, i fixed it by:
1.  AbstractComponent.php
change `15: use Phalcon\Config;` to `use Phalcon\Config\Config;`
2.  ProjectBuilder.php
change `15: use Phalcon\Config;` to `use Phalcon\Config\Config;`
3.  BuilderException.php
change `15: use Phalcon\Exception;` to `use Phalcon\Config\Exception;`

And project was created. But i dont check another commands. May be, there are still some bugs

**Comment by daleffe** [comment]
Hi friends,

For Phalcon 5.x you can use [this version](https://github.com/daleffe/phalcon-devtools-5.x-fixed).
