### ISSUE TITLE
Error on trying generate model

### ISSUE THREAD

**Issue by dellert** [phalcon/phalcon-devtools#706]
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on integer in /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Builder/Model.php:138
Stack trace:
#0 /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Commands/Builtin/Model.php(96): Phalcon\Builder\Model->build()
#1 /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Script.php(125): Phalcon\Commands\Builtin\Model->run(Array)
#2 /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Script.php(150): Phalcon\Script->dispatch(Object(Phalcon\Commands\Builtin\Model))
#3 /vagrant/vendor/phalcon/devtools/phalcon.php(86): Phalcon\Script->run()
#4 {main}
  thrown in /vagrant/vendor/phalcon/devtools/scripts/Phalcon/Builder/Model.php on line 138
```

**Comment by sergeyklay** [comment]
What version of devtools?

**Comment by dellert** [comment]
for in composer set ^2.0

**Comment by sergeyklay** [comment]
@dellert What version of Phalcon?

**Comment by dellert** [comment]
2.1

**Comment by sergeyklay** [comment]
So you have to use Devtools 2.1.x

**Comment by dellert** [comment]
such error

**Comment by dellert** [comment]
I have no config.php. I have anoter structure. So, I have to rewrite code for me. Thanks
