### ISSUE TITLE
Migration generate bug

### ISSUE THREAD

**Issue by dcosta-ptc** [phalcon/phalcon-devtools#747]
Hi,

On 3.0.x using generate i get this:

```
PHP Fatal error:  Uncaught Error: Undefined class constant 'MIGRATION_LOG_TABLE' in /vendor/phalcon/devtools/scripts/Phalcon/Migrations.php:134
Stack trace:
#0 /vendor/phalcon/devtools/scripts/Phalcon/Commands/Builtin/Migration.php(129): Phalcon\Migrations::generate(Array)
#1 /vendor/phalcon/devtools/scripts/Phalcon/Script.php(125): Phalcon\Commands\Builtin\Migration->run(Array)
#2 /vendor/phalcon/devtools/scripts/Phalcon/Script.php(150): Phalcon\Script->dispatch(Object(Phalcon\Commands\Builtin\Migration))
#3 /vendor/phalcon/devtools/phalcon.php(95): Phalcon\Script->run()
#4 {main}
  thrown in /vendor/phalcon/devtools/scripts/Phalcon/Migrations.php on line 134
```

No constant `MIGRATION_LOG_TABLE` only a static variable found `$migration_log_table`.

**Comment by sergeyklay** [comment]
Thanks! Fixed in the `3.0.x` branch.
