### ISSUE TITLE
SQLSTATE[08006] [7] invalid connection option "charset" - PostgreSQL

### ISSUE THREAD

**Issue by alisovpv** [phalcon/phalcon-devtools#990]
### SQLSTATE[08006] [7] invalid connection option "charset" - PostgreSQL

>After creating the project and the webtools I go through the site address mysite.com/webtools.php, works, switch to the Models tab  and get this error

```php
PDOException: SQLSTATE[08006] [7] invalid connection option "charset"
#0 [internal function]: PDO->__construct('pgsql:host=loca...', 'my_username', 'my_password', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\Postgresql->connect(Array)
#3 /home/fix/phalcon-devtools/scripts/Phalcon/Web/Tools.php(347): Phalcon\Db\Adapter\Pdo->__construct(Array)
#4 [internal function]: Phalcon\Web\Tools->Phalcon\Web\{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('db', NULL)
#7 /home/fix/phalcon-devtools/scripts/Phalcon/Web/Tools.php(190): Phalcon\Di->getShared('db')
#8 /home/fix/phalcon-devtools/scripts/Phalcon/Web/Tools/controllers/ControllerBase.php(122): Phalcon\Web\Tools::getConnection()
#9 /home/fix/phalcon-devtools/scripts/Phalcon/Web/Tools/controllers/ModelsController.php(30): ControllerBase->listTables(true)
#10 [internal function]: ModelsController->indexAction()
#11 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(ModelsController), 'indexAction', Array)
#12 [internal function]: Phalcon\Dispatcher->_dispatch()
#13 [internal function]: Phalcon\Dispatcher->dispatch()
#14 /home/fix/phalcon-devtools/scripts/Phalcon/Web/Tools.php(356): Phalcon\Mvc\Application->handle()
#15 /var/www/phalcon.work/public/webtools.php(26): Phalcon\Web\Tools::main('/home/fix/phalc...', '192.168.')
#16 {main}
```
> config.php

```php
defined('APP_PATH') || define('APP_PATH', realpath('.'));

return new \Phalcon\Config([
    'database' => [
        'adapter'     => 'Postgresql',
        'host'        => 'localhost',
        'username'    => 'my_username',
        'password'    => 'my_password',
        'dbname'      => 'webpack',
    ],
    'application' => [
        'controllersDir' => APP_PATH . '/app/controllers/',
        'modelsDir'      => APP_PATH . '/app/models/',
        'migrationsDir'  => APP_PATH . '/app/migrations/',
        'viewsDir'       => APP_PATH . '/app/views/',
        'pluginsDir'     => APP_PATH . '/app/plugins/',
        'libraryDir'     => APP_PATH . '/app/library/',
        'cacheDir'       => APP_PATH . '/app/cache/',
        'baseUri'        => '/web.pack/',
    ]
]);
```
> I tried to add the option of charset in different versions, the result is the same
```php
 'charset'      => 'utf8',
```
>or
```php
 'charset'      => 'utf-8',
```
DB encoding - UTF-8, Collate - ru_RU.UTF-8, Ctype - ru_RU.UTF-8
I tried without Phalcon to run the code, everything worked fine
```php
$dbh = new PDO('pgsql:host=localhost;port=5432;dbname=webpack', 'my_username', 'my_password');
    foreach($dbh->query('SELECT * from users') as $row) {
        print_r($row);
    }
```
### Details

* Phalcon Framework version: 3.0.0
* PHP Version: 7.0.16
* Operating System: Ubuntu 14.04
* Server: Nginx 
* Other related info (Database, table schema):  PosgreSQL 9.5

**Comment by sergeyklay** [comment]
I'll try to sort out as soon as I can

**Comment by alisovpv** [comment]
Не дождался решения от вас, решил попробовать на рабочей машине, конфиг тот же, единственное изменение это 
Phalcon DevTools Version	3.1.0
Phalcon Version	3.1.1
но теперь вместо ошибки просто белый экран. Вобщем какая то беда со связкой Phalcon + PostgreSQL

**Comment by alisovpv** [comment]
В версии 3.1.1 проблема решилась удалением конфига 'charset', без него все работает, в 3.0.0 этот фокус не проходит. Проблема решена, топик можно закрывать.

**Comment by sergeyklay** [comment]
> ERROR: SQLSTATE[08006] [7] invalid connection option "charset"

https://github.com/phalcon/phalcon-devtools#database-adapter

**Comment by moledet** [comment]
Таже проблема Phalcon Framework 3.3.2
PDOException: SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xf0 0xba 0xf0 0xb8
Притом на 3.1 все работает нормально,  'charset'     => 'utf8' не помогает
